Blog app - integration specs for views and fix n+1 problems
belmeetmule/Blog-App pull request #10
Opened 2023-02-07 15:34 UTC by belmeetmule

In this PR, I and my coding partner have done the following activities:

- [ ] solved the N+1 problem caused when fetching all posts and their comments for a user
**Before the N+1 problem is solved !**
![n-plus-one-before](https://user-images.githubusercontent.com/97679679/217288814-f2f3258c-c8df-40e2-a696-34f06797a309.PNG)
**After the N+1 problem is solved !**
![n-plus-one-after](https://user-images.githubusercontent.com/97679679/217289085-1b939f11-7acd-4ab1-9167-f78dd5e4c25e.PNG)

- [ ] Integration specs

-  **Configured Capybara**
- **Wrote integration tests for each view of the project**

2023-02-07 16:25 UTC, Rustamxon7 requested changes
Hello @belmeetmule,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
_Your project is almost complete!_
_No Linters errors_

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Check the comments under the review._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-07 16:25 UTC, rustam-tolipov commented on README.md
> -<a name="readme-top"></a>
**You did a great job!**
However, we have some cleaning jobs to do. 

- [ ] Kindly remove commented code from your `index.html.erb_spec.rb`:


<img width="432" alt="Screenshot 2023-02-07 at 20 48 55" src="https://user-images.githubusercontent.com/69011963/217294537-00604f8c-0c3d-4561-8a8d-7558531d0dd5.png">

2023-02-07 16:25 UTC, rustam-tolipov commented on README.md
> -
- [ ] In requests/posts_spec.rb
Kindly remove unused commented codes!

<img width="574" alt="Screenshot 2023-02-07 at 20 49 22" src="https://user-images.githubusercontent.com/69011963/217294769-058c3945-fe95-473f-8271-8cfae422d265.png">

2023-02-07 16:25 UTC, rustam-tolipov commented on README.md
> -HOW TO USE:
- [ ] In request/comments_spec.rb
Kindly remove unused commented codes!

<img width="643" alt="Screenshot 2023-02-07 at 20 49 30" src="https://user-images.githubusercontent.com/69011963/217294925-92969a19-e6c3-44e3-8e3a-f90928bff872.png">

2023-02-07 16:25 UTC, rustam-tolipov commented on README.md
> -
- [ ] When we generate modes with scaffold it creates some unnecessary helpers. At that point, I think these files are not necessary for us to keep. Kindly remove them as well.

<img width="274" alt="Screenshot 2023-02-07 at 20 49 46" src="https://user-images.githubusercontent.com/69011963/217295174-bbf8c806-9c66-42fc-80a6-fc1789829d4a.png">

2023-02-07 18:57 UTC, omarsalem7 approved these changes
Hi @belmeetmule 😊, 
# STATUS: APPROVED! 🥇 💯 

![giphy](https://media.giphy.com/media/n5VaQoW39Z9S0/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 🚀 
Congratulations! 🎉 

## Highlights
✅ Descriptive pull request 
✅ Project has met all the technical aspects you needed for this project. Keep rocking! 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-07 18:59 UTC, merged

2023-04-10 15:56 UTC, rloterh reviewed
Hi Mulugeta, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

Kindly ensure that your ReadMe is professionally documented:
- Kindly ensure that provided placeholder texts/ guide instructions are removed and/or replaced with appropriate contents applicable under each section of your ReadMe. 

![image](https://user-images.githubusercontent.com/12745474/230939914-bfe01af5-d061-44b5-b777-37a325ae82d1.png)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._